version: '2'

services:

  syf-pg:
    image: postgres
    environment:
      POSTGRES_DB: rps
      POSTGRES_USER: rps
      POSTGRES_PASSWORD: rps
#    volumes:
        

  syf-ws:
    image: jboss/wildfly
    command: /opt/jboss/wildfly/bin/domain.sh -b 0.0.0.0 -bmanagement 0.0.0.0
    ports:
      - 8080:8080
      - 8180:8180
      - 9990:9990
      - 9999:9999
    volumes:
      - ./wildfly/org:/opt/jboss/wildfly/modules/org
      - ./wildfly/rps-ear.ear:/opt/jboss/wildfly/domain/deployments/rps-ear.ear
      - ./wildfly/host.xml:/opt/jboss/wildfly/domain/configuration/host.xml
      - ./wildfly/domain.xml:/opt/jboss/wildfly/domain/configuration/domain.xml
      - ./wildfly/mgmt-groups.properties:/opt/jboss/wildfly/domain/configuration/mgmt-groups.properties
      - ./wildfly/mgmt-users.properties:/opt/jboss/wildfly/domain/configuration/mgmt-users.properties

# Partie à faire coder aux stagiaires

#  syf-ui:
#    build: ./nginx
#    ports:
#      - 80:80
